# copy paste from https://hub.docker.com/_/postgres
# Use postgres/example user/password credentials
services:
  postgres:
    image: postgres #:alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      PGUSER: user
      POSTGRES_PASSWORD: password
    # env_file:
    #   - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  flyway-migrations:
    image: flyway/flyway
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: -url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -X migrate
    # -schema=$(POSTGRES_SCHEMA)