name: ci

on:
  push:
    branches:
      - master

jobs:
  build-rusteu:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - 
        name: Set short git commit SHA
        id: vars
        run: |
          echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - 
        name: Build rusteu
        uses: docker/build-push-action@v6
        with:
          push: true
          context: server
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_rusteu:latest, ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_rusteu:${{ env.COMMIT_SHORT_SHA }}
          cache-from: type=registry,ref=${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_rusteu:latest
          cache-to: type=inline
  
  build-sveltekit:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - 
        name: Set short git commit SHA
        id: vars
        run: |
          echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - 
        name: Build sveltekit
        uses: docker/build-push-action@v6
        with:
          push: true
          context: app
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_sveltekit:latest, ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_sveltekit:${{ env.COMMIT_SHORT_SHA }}
          cache-from: type=registry,ref=${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_sveltekit:latest
          cache-to: type=inline

  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: [build-rusteu, build-sveltekit]
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "nginx_conf=$(base64 -w0 nginx.conf)" >> $GITHUB_OUTPUT
      - 
        name: Render template
        id: render_template
        uses: chuhlomin/render-template@v1.7
        with:
          template: compose.yaml.template
          vars: |
            rusteu_image: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_rusteu:latest
            sveltekit_image: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_sveltekit:latest
          # ${{ steps.vars.outputs.sha_short }}
      - 
        name: run commands to deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf nginx.conf
            echo ${{ steps.vars.outputs.nginx_conf }} | base64 -d > nginx.conf
            mkdir -p db && echo ${{ secrets.DB_SECRET }} > db/password.txt
            echo "${{ steps.render_template.outputs.result }}" > compose.yaml
            docker-compose pull
            docker compose up -d