name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - 
        uses: actions/checkout@v2
      
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - 
        name: Set short git commit SHA
        id: vars
        run: |
          echo "COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - 
        name: Build sveltekit
        uses: docker/build-push-action@v6
        with:
          push: true
          context: app
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_sveltekit:${{ env.COMMIT_SHORT_SHA }}
          
      - 
        name: Build rusteu
        uses: docker/build-push-action@v6
        with:
          push: true
          context: server
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_rusteu:${{ env.COMMIT_SHORT_SHA }}
      
  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: build
    steps:
      -        
        name: Set short git commit SHA
        id: vars
        run: |
          echo "COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Render template
        id: render_template
        uses: chuhlomin/render-template@v1.7
        with:
          template: compose.yaml.template
          vars: |
            rusteu_image: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_rusteu:${{ env.COMMIT_SHORT_SHA }}
            sveltekit_image: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}_sveltekit:${{ env.COMMIT_SHORT_SHA }}

      - name: run commands to deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker container prune -f ; docker image prune -f -a ; echo "${{ steps.render_template.outputs.result }}" | docker stack deploy --with-registry-auth --resolve-image always -c - cn